### ISSUE TITLE
daily usage?

### ISSUE THREAD

**Issue by scsi050** [bachya/pyxcel#1]
Hi, this works great for getting monthly usage but I don't see any daily usage returned, yet it is visible in the account usage graphs on xcel's site.

Is it possible to pull that daily data back as well?
thanks

**Comment by bachya** [comment]
Hi there. Unfortunately, Xcel's private back-end is _very_ restricted. The data you see in this library is what's possible (to my knowledge) today. Sorry!

**Comment by scsi050** [comment]
understood. I'm trying to get this into Home Assistant, which I see you're a member of. I guess it would be great if HA had this Xcel connectivity as a sanctioned integration. fun fun

**Comment by bachya** [comment]
100% agreed. I never built the integration because the Xcel API is too difficult to reliably reverse-engineer.
